import type { CSSProperties } from 'react';
import type { ColorScale } from './color-themes';

export function buildPrismTheme(colors: ColorScale): Record<string, CSSProperties> {
  return {
    'code[class*="language-"]': {
      color: colors.textPrimary,
      fontFamily: "var(--font-mono)",
      fontSize: '0.9em',
      lineHeight: '1.6',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      tabSize: 2,
    },
    'pre[class*="language-"]': {
      color: colors.textPrimary,
      fontFamily: "var(--font-mono)",
      fontSize: '0.9em',
      lineHeight: '1.6',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      tabSize: 2,
      padding: '16px',
      margin: '0',
      overflow: 'auto',
      background: colors.bgSecondary,
      borderRadius: '6px',
    },
    comment: { color: colors.codeComment, fontStyle: 'italic' },
    prolog: { color: colors.codeComment },
    doctype: { color: colors.codeComment },
    cdata: { color: colors.codeComment },
    punctuation: { color: colors.codePunctuation },
    property: { color: colors.codeKeyword },
    tag: { color: colors.codeKeyword },
    boolean: { color: colors.codeNumber },
    number: { color: colors.codeNumber },
    constant: { color: colors.codeNumber },
    symbol: { color: colors.codeNumber },
    selector: { color: colors.codeString },
    'attr-name': { color: colors.codeFunction },
    string: { color: colors.codeString },
    char: { color: colors.codeString },
    builtin: { color: colors.codeKeyword },
    inserted: { color: colors.codeString },
    operator: { color: colors.codePunctuation },
    entity: { color: colors.codePunctuation },
    url: { color: colors.codeNumber },
    '.language-css .token.string': { color: colors.codeNumber },
    '.style .token.string': { color: colors.codeNumber },
    atrule: { color: colors.codeKeyword },
    'attr-value': { color: colors.codeString },
    keyword: { color: colors.codeKeyword, fontWeight: 600 },
    function: { color: colors.codeFunction },
    'class-name': { color: colors.codeKeyword },
    regex: { color: colors.codeFunction },
    important: { color: colors.error, fontWeight: 'bold' as const },
    variable: { color: colors.textPrimary },
    bold: { fontWeight: 'bold' as const },
    italic: { fontStyle: 'italic' as const },
    deleted: { color: colors.error },
  };
}
